// <auto-generated />
using System;
using GradeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradeService.Infrastructure.Migrations
{
    [DbContext(typeof(GradeDbContext))]
    [Migration("20250521190025_gradeServiceMigration")]
    partial class gradeServiceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradeService.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateGraded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GradeValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c53ef888-3f6e-4f72-8cf4-da1e5f03ca16"),
                            Comments = "Excellent performance",
                            CourseId = new Guid("0365eed4-e67d-460a-abd7-6742b3698d86"),
                            DateGraded = new DateTime(2025, 5, 20, 17, 59, 0, 0, DateTimeKind.Utc),
                            GradeValue = 90.0m,
                            StudentId = new Guid("b1c2d3e4-f5f6-7890-abcd-ef1234567890")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
