// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentService.Infrastructure.Persistence;

#nullable disable

namespace StudentService.Infrastructure.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260426112831_ProfileUpdateWithStudentModel")]
    partial class ProfileUpdateWithStudentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentService.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28c58647-ddc6-43b4-b694-4c2a42cef6c5"),
                            UserId = new Guid("b1c2d3e4-f5f6-7890-abcd-ef1234567890")
                        },
                        new
                        {
                            Id = new Guid("79841481-3f79-47eb-ba04-e215e6432c49"),
                            UserId = new Guid("c2d3e4f5-f678-90ab-cdef-1234567890ab")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
