ARG DOTNET_RUNTIME=mcr.microsoft.com/dotnet/aspnet:9.0
ARG DOTNET_SDK=mcr.microsoft.com/dotnet/sdk:9.0

FROM ${DOTNET_RUNTIME} AS base
WORKDIR /app
EXPOSE 8080

# Base for build
FROM ${DOTNET_SDK} AS buildbase
WORKDIR /app

COPY ["src/ReportService.API/ReportService.API.csproj", "src/ReportService.API/ReportService.API.csproj"]
COPY ["src/ReportService.Application/ReportService.Application.csproj", "src/ReportService.Application/ReportService.Application.csproj"]
COPY ["src/ReportService.Domain/ReportService.Domain.csproj", "src/ReportService.Domain/ReportService.Domain.csproj"]
COPY ["src/ReportService.Infrastructure/ReportService.Infrastructure.csproj", "src/ReportService.Infrastructure/ReportService.Infrastructure.csproj"]

RUN dotnet restore src/ReportService.API/ReportService.API.csproj
RUN dotnet restore src/ReportService.Application/ReportService.Application.csproj
RUN dotnet restore src/ReportService.Domain/ReportService.Domain.csproj
RUN dotnet restore src/ReportService.Infrastructure/ReportService.Infrastructure.csproj

COPY ["src/", "src/"]

## Run migrations
FROM buildbase as migrations
RUN dotnet tool install --version 9.0.1 --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
ENTRYPOINT dotnet-ef database update --project src/ReportService.Infrastructure/ --startup-project src/ReportService.API/