// <auto-generated />
using System;
using EnrollmentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnrollmentService.Infrastructure.Migrations
{
    [DbContext(typeof(EnrollmentDbContext))]
    [Migration("20250513182545_enrollmentServiceMigration")]
    partial class enrollmentServiceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnrollmentService.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c7890df-40ca-48ab-88d2-ff510fd4f818"),
                            CourseId = new Guid("0365eed4-e67d-460a-abd7-6742b3698d86"),
                            EnrollmentDate = new DateTime(2025, 5, 13, 11, 58, 0, 0, DateTimeKind.Utc),
                            Status = "Enrolled",
                            StudentId = new Guid("b1c2d3e4-f5f6-7890-abcd-ef1234567890")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
