ARG DOTNET_RUNTIME=mcr.microsoft.com/dotnet/aspnet:9.0
ARG DOTNET_SDK=mcr.microsoft.com/dotnet/sdk:9.0

FROM ${DOTNET_RUNTIME} AS base
WORKDIR /app
EXPOSE 8080

# Base for build
FROM ${DOTNET_SDK} AS buildbase
WORKDIR /app

COPY ["src/CourseService.API/CourseService.API.csproj", "src/CourseService.API/CourseService.API.csproj"]
COPY ["src/CourseService.Application/CourseService.Application.csproj", "src/CourseService.Application/CourseService.Application.csproj"]
COPY ["src/CourseService.Domain/CourseService.Domain.csproj", "src/CourseService.Domain/CourseService.Domain.csproj"]
COPY ["src/CourseService.Infrastructure/CourseService.Infrastructure.csproj", "src/CourseService.Infrastructure/CourseService.Infrastructure.csproj"]

RUN dotnet restore src/CourseService.API/CourseService.API.csproj
RUN dotnet restore src/CourseService.Application/CourseService.Application.csproj
RUN dotnet restore src/CourseService.Domain/CourseService.Domain.csproj
RUN dotnet restore src/CourseService.Infrastructure/CourseService.Infrastructure.csproj

COPY ["src/", "src/"]

## Run migrations
FROM buildbase as migrations
RUN dotnet tool install --version 9.0.1 --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
ENTRYPOINT dotnet-ef database update --project src/CourseService.Infrastructure/ --startup-project src/CourseService.API/