name: CI Pipeline for SRMS App

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner (Ubuntu)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repo code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Setup Docker Buildx for multi-platform builds
        with:
          version: latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl  # Ensure curl is installed
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3  # Setup .NET SDK (use v3 if you are using .NET 9)
        with:
          dotnet-version: '9.0'

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build  # Build the services

      - name: Start services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # Start services in detached mode

      - name: Wait for services to be ready
        run: |
          # Set maximum retry count and timeout for pg_isready
          MAX_RETRIES=30
          RETRY_COUNT=0
          WAIT_INTERVAL=2

          # Wait for PostgreSQL (authdb) to be ready
          until pg_isready -h authdb -U postgres || [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
            echo "waiting for authdb ($RETRY_COUNT/$MAX_RETRIES)..."
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep $WAIT_INTERVAL
          done

          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
            echo "AuthDB is not ready after $MAX_RETRIES retries, exiting."
            exit 1
          fi

          RETRY_COUNT=0
          # Wait for PostgreSQL (userdb) to be ready
          until pg_isready -h userdb -U postgres || [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
            echo "waiting for userdb ($RETRY_COUNT/$MAX_RETRIES)..."
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep $WAIT_INTERVAL
          done

          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
            echo "UserDB is not ready after $MAX_RETRIES retries, exiting."
            exit 1
          fi

          RETRY_COUNT=0
          # Wait for Redis to be ready
          until redis-cli -h redis ping || [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
            echo "waiting for redis ($RETRY_COUNT/$MAX_RETRIES)..."
            RETRY_COUNT=$((RETRY_COUNT+1))
            sleep $WAIT_INTERVAL
          done

          if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
            echo "Redis is not ready after $MAX_RETRIES retries, exiting."
            exit 1
          fi

          echo "All services are ready!"

      - name: Restore .NET dependencies
        run: dotnet restore  # Restore NuGet dependencies

      - name: Build the project
        run: dotnet build --configuration Release  # Build the project

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal  # Run tests without rebuilding the solution

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: $(System.DefaultWorkingDirectory)/TestResults/*.xml

      - name: Stop and remove Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down  # Clean up the services after tests are done
